todo view and source navigation
thonny/thonny pull request #2067
Opened 2021-12-06 10:12 UTC by kr-g

this adds a new view in south panel where all todo's from the source are extracted and shown in a list.
when clicking on a todo (list item) the corresponsing line in editor code view is selected.

2021-12-10 05:19 UTC, aivarannamaa commented
This is good goal! Not really a beginner's thing, but as it's not prominent it's OK. 

Please keep different features separated in PR-s!

2021-12-10 05:23 UTC, aivarannamaa commented
In case the file doesn't have any TODO-s, I would show a single item, which describes the purpose of this view.

2021-12-12 13:56 UTC, kr-g commented
Feel free to change !
For me it is already fine in the current state.

2022-04-01 07:42 UTC, kr-g commented
> In case the file doesn't have any TODO-s, I would show a single item, which describes the purpose of this view.

as supposed by you @aivarannamaa

2022-08-09 07:32 UTC, kr-g commented
cleaned PR from unrelated source

RFC

2022-08-14 05:54 UTC, aivarannamaa requested changes

2022-08-14 07:59 UTC, kr-g commented on thonny/plugins/todo_view.py
> +    get_workbench().add_view(TodoView, tr("Todo's"), "s")
i m also not 100% sure regarding this.
so i checked that (german version)

https://english.lingolia.com/de/schreibschule/zeichensetzung/apostroph
https://dict.leo.org/grammatik/englisch/nouns_plural_context.php?lang=de#id=2.1.4.d

well... could be right or not.

how about just "TODO" ?

2022-08-14 08:21 UTC, kr-g commented on thonny/plugins/todo_view.py
> +        new_source = new_cw.get_content_as_bytes()
i made that PR half year ago. 
i have no idea why i made that decision.

2022-08-14 10:56 UTC, kr-g commented on thonny/plugins/todo_view.py
> +        # todo: not updated on first run
done

2022-08-14 10:56 UTC, kr-g commented on thonny/plugins/todo_view.py
> +        new_source = new_cw.get_content_as_bytes()
removed

2022-08-14 10:57 UTC, kr-g commented on thonny/plugins/todo_view.py
> +
done

2022-08-14 10:57 UTC, kr-g commented on thonny/plugins/todo_view.py
> +    get_workbench().add_view(TodoView, tr("Todo's"), "s")
change to TODO

2022-08-14 10:59 UTC, kr-g commented
ok thanks for the feedback.
learned a bit more about events.

RFC

2022-08-14 15:51 UTC, merged

2022-08-14 15:51 UTC, aivarannamaa commented
Thank you!