Switch to the Tcl modernText library
thonny/thonny pull request #2768
Opened 2023-05-02 11:51 UTC by mrexodia

Reference: https://wiki.tcl-lang.org/page/Modern+Bindings+for+the+Text+Widget

Closes #2639

2023-05-07 17:49 UTC, aivarannamaa commented
Thanks for this effort!

Unfortunately I can't promise I can review this soon (it need lot of attention) and I'm not even sure I dare to use this approach.

modernText.tcl seems to be rather old and I'm afraid we could lose some other fixes and updates if we switch.

Nevertheless, I'll take a look once I have more free time.

2023-05-07 18:18 UTC, mrexodia commented
What about merging it behind a checkbox? Most likely there is an updated version of `modernText`, although I think all of Tcl is actually ancient (2012 from what I can see) so I don’t think there will be any meaningful features added…

2023-07-11 02:48 UTC, Moosems commented
Certainly an interesting idea. It might be better to just make binds to the Text that override the default by using bind_class and therefore changing the default behavior.

2024-11-22 18:29 UTC, Unrud commented
This also fixes https://github.com/thonny/thonny/issues/2996.

2024-12-10 03:23 UTC, mrexodia commented
Any updates on this?

2025-01-15 16:19 UTC, mrexodia commented
I’m happy to rebase this or do additional tests etc. From my research the latest editor in Tcl is **much** older than modernText, but I’m happy to add a setting to revert to the default one.

2025-01-15 16:24 UTC, aivarannamaa commented
A rebase would be good!

2025-01-15 19:15 UTC, mrexodia commented
Alright, done!

2025-01-15 20:36 UTC, aivarannamaa commented on thonny/workbench.py
> +
Could you please extract this into separate method?

2025-01-15 20:37 UTC, aivarannamaa commented on thonny/tktextext.py
> +        # Reference: https://wiki.tcl-lang.org/page/Modern+Bindings+for+the+Text+Widget
Is all of this required for each instance of Text?

2025-01-15 20:37 UTC, aivarannamaa requested changes
Please check my comments

2025-01-15 23:55 UTC, mrexodia commented on thonny/tktextext.py
> +        # Reference: https://wiki.tcl-lang.org/page/Modern+Bindings+for+the+Text+Widget
If I remember correctly the `self.bindtags` is required every time a new text instance is created.

2025-01-15 23:57 UTC, mrexodia commented on thonny/workbench.py
> +
Done!

2025-01-30 11:50 UTC, mrexodia commented
I made the changes you requested, could you re-review @aivarannamaa?

2025-02-04 16:15 UTC, aivarannamaa commented
It looks like I botched the PR with my rebase somehow. I'll handle this.

2025-02-04 16:59 UTC, aivarannamaa commented
I now investigated https://wiki.tcl-lang.org/page/Modern+Bindings+for+the+Text+Widget more closely and noticed

> [KJN](https://wiki.tcl-lang.org/page/KJN): See [ntext](https://wiki.tcl-lang.org/page/ntext) for the completed version of this package.
> 
> * The tasks in the "To Do" list below have been completed (except writing the TIP; feedback from users would be helpful before the TIP is written).
> * The package has been renamed from "modernText" to "ntext" to avoid confusion with the Computer Modern fonts (my thanks to the person who pointed this out).

* https://core.tcl-lang.org/tklib/doc/trunk/embedded/md/tklib/files/modules/ntext/ntext.md
* https://core.tcl-lang.org/tklib/doc/trunk/embedded/md/tklib/files/modules/ntext/ntextBindings.md
* https://core.tcl-lang.org/tklib/doc/trunk/embedded/md/tklib/files/modules/ntext/ntextIndent.md
* https://core.tcl-lang.org/tklib/doc/trunk/embedded/md/tklib/files/modules/ntext/ntextWordBreak.md
* https://github.com/tcltk/tklib/tree/master/modules/ntext

Thanks for bringing my attention to this, but I'll close this PR, hoping to investigate ntext after Thonny 5.0 gets released.

2025-02-04 16:59 UTC, closed without merging